version: '3'

services:
  bera_gov_alerter_backend:
    container_name: bera_gov_alerter_backend
    build: .
    volumes:
      - ./:/home/bera_gov_alerter_backend
      - /home/bera_gov_alerter_backend/node_modules
    working_dir: /home/bera_gov_alerter_backend
    environment:
      - POSTGRES_HOST=bera_gov_alerter_db
    depends_on:
      - bera_gov_alerter_database
    env_file:
      - .env

  bera_gov_alerter_database:
    container_name: bera_gov_alerter_db
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
